### ISSUE TITLE
输出指标异常

### ISSUE THREAD

**Issue by zj13** [Sherry-XLL/Social-Datasets#1]
您好，在使用不同模型跑yelp和flickr的数据集时，ndcg等输出指标都非常的小，在0.03以下，而filmtrust和lastfm小数据集指标则正常，很疑惑是否是数据集处理问题？还是config设置问题？用diffnet作者代码跑yelp的指标并没有那么小，期待您的解答~

**Comment by Sherry-XLL** [comment]
@zj13 您好，yelp 和 flickr 的数据集和 [diffnet](https://github.com/PeiJieSun/diffnet) 所提供的数据集完全一致，如果要复现作者原文的结果，请确保预处理的设置参数和源论文保持一致。

**Comment by Sherry-XLL** [comment]
@zj13 您好，yelp 和 flickr 的数据集和 [diffnet](https://github.com/PeiJieSun/diffnet) 所提供的数据集完全一致，如果要复现作者原文的结果，请确保预处理的设置参数和源论文保持一致。

**Comment by zj13** [comment]
非常感谢您的解答！
